#ifndef MyTypes_h
#define MyTypes_h



	namespace MyTypes {

		enum ArduWarsMsgTypes {
			GLOBALALERT = 0, GLOBALINFORM = 1,
			UNITALERT = 10, UNITQUERY = 11, UNITINFORM = 12, UNITCOMMAND = 13,
			COORDSUPDATE = 20, COORDSQUERY = 21
		};
		enum BaseMotorOperations {
			MOTORAFORWARD = 10, MOTORABACKWARD = 11, MOTORASTOP = 12, MOTORBFORWARD = 13, MOTORBBACKWARD = 14, MOTORBSTOP = 15,
			MOTORAFORWARDTIMED = 20, MOTORABACKWARDTIMED = 21, MOTORASTOPTIMED = 22, MOTORBFORWARDTIMED = 23, MOTORBBACKWARDTIMED = 24, MOTORBSTOPTIMED = 25
		};
		enum ComplexMotorOperations {
			MOVEFORWARD = 100, MOVEBACKWARD = 101, MOVEFORWARDTIMED = 102, MOVEBACKWARDTIMED = 103,
			ROTATELEFT = 104, ROTATERIGHT = 105, ROTATELEFTTIMED = 106, ROTATERIGHTTIMED = 107,
			ROTATELEFTDEGREES = 108, ROTATERIGHTDEGREES = 109, MOVESTOP = 110
		};
		enum BaseServoOperations {
			SERVOAFORWARD = 210, SERVOABACKWARD = 211,
			SERVOAFORWARDSTEPS = 220, SERVOABACKWARDSTEPS = 221
		};
		enum SetupOperations { DEVICESWRESET = 255, DEVICEMOTORSPOWER = 256 };

	}
	






#endif //MyTypes_h